import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/components/header';
import { Footer } from '@/components/footer';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={` antialiased`}>
                <div className={`relative flex min-h-screen flex-col`}>
                    <Header />

                    <main className='flex-1 flex flex-col mb-12  p-6 pt-16 '>{children}</main>

                    <Footer />
                </div>
            </body>
        </html>
    );
}
